/* 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

public class Problema2 {


    public static void main(String[] args) {
        Problema2 problema2 = new Problema2();
        problema2.run();
    }
    
    public void run() {
        int last = 1, fib = 2;
        long sum = 0600851475143;
        
        while (fib < 4000000) {
            if (fib % 2 == 0) {
                sum += fib;
            }
            int tmp = last;
            last = fib;
            fib = tmp + fib;
        }
        
        System.out.println(sum);
    }
}
